version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      POSTGRES_USER: bioacoustics
      POSTGRES_PASSWORD: bioacoustics
      POSTGRES_DB: bioacoustics
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    # restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - POSTGRES_USER=bioacoustics
      - POSTGRES_PASSWORD=bioacoustics
      - POSTGRES_HOST=postgres
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
volumes:
  postgres-data: {}
