site_name: bioacoustics
site_description: Google Bioacoustics API
repo_url: https://github.com/developmentseed/bioacoustics-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/developmentseed">developmentseed</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
